name: Solar System Workflow
env:
  MONGO_URI: mongodb+srv://supercluster.d83jj.mongodb.net/superData
  MONGO_USERNAME: superuser
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
    
jobs:     
    unit-testing:
        name: Unit Testing
        runs-on: ubuntu-latest
        container:
          image: 'node:20'
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        #- name: Setup NodeJS Version
        #  uses: actions/setup-node@v3
        #  with:
        #    node-version: 20

        - name: Cache NPM dependencies
          uses: actions/cache@v4
          with:
            path: ~/.npm
            key: '${{ runner.os }}-node-modules-${{ hashFiles(''package-lock.json'') }}'
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result
          if: always()
          uses: actions/upload-artifact@v3
          with:
            name: Mocha-Test-Result
            path: test-results.xml
            
    code-coverage:
        name: Code Coverage
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
          
        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: 18
            
        - name: Install Dependencies
          run: npm install

        - name: Code Coverage
          run: npm run coverage
          continue-on-error: true

        - name: Archive Test Result
          if: always()
          uses: actions/upload-artifact@v3
          with:
            name: Code-Coverage-Result
            path: coverage
            retention-days: 5

    docker:
        permissions: #added
          packages: write #added
        name: docker
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Set lowercase repository owner
          run: echo "REPO_OWNER_LC=jaruwat-panturat" >> $GITHUB_ENV
        - name: Docker login
          uses: docker/login-action@v3
          with:
            registry: 'ghcr.io'
            username: '${{ github.repository_owner }}'
            password: '${{ secrets.GH_TOKEN }}'
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            context: .
            push: true
            tags: "ghcr.io/${{ env.REPO_OWNER_LC }}/solar-system:${{ github.sha }}"
          
    
